city:
    path:     /
    defaults: { _controller: "pizzaSiteBundle:City:index" }

city_show:
    path:     /{id}/show
    defaults: { _controller: "pizzaSiteBundle:City:show" }

city_new:
    path:     /new
    defaults: { _controller: "pizzaSiteBundle:City:new" }

city_create:
    path:     /create
    defaults: { _controller: "pizzaSiteBundle:City:create" }
    requirements: { _method: post }

city_edit:
    path:     /{id}/edit
    defaults: { _controller: "pizzaSiteBundle:City:edit" }

city_update:
    path:     /{id}/update
    defaults: { _controller: "pizzaSiteBundle:City:update" }
    requirements: { _method: post|put }

city_delete:
    path:     /{id}/delete
    defaults: { _controller: "pizzaSiteBundle:City:delete" }
    requirements: { _method: post|delete }
