customer:
    path:     /
    defaults: { _controller: "pizzaSiteBundle:Customer:index" }

customer_show:
    path:     /{id}/show
    defaults: { _controller: "pizzaSiteBundle:Customer:show" }

customer_new:
    path:     /new
    defaults: { _controller: "pizzaSiteBundle:Customer:new" }

customer_create:
    path:     /create
    defaults: { _controller: "pizzaSiteBundle:Customer:create" }
    requirements: { _method: post }

customer_edit:
    path:     /{id}/edit
    defaults: { _controller: "pizzaSiteBundle:Customer:edit" }

customer_update:
    path:     /{id}/update
    defaults: { _controller: "pizzaSiteBundle:Customer:update" }
    requirements: { _method: post|put }

customer_delete:
    path:     /{id}/delete
    defaults: { _controller: "pizzaSiteBundle:Customer:delete" }
    requirements: { _method: post|delete }
