pizza:
    path:     /
    defaults: { _controller: "pizzaSiteBundle:Pizza:index" }

pizza_home:
    path:     /home
    defaults: { _controller: "pizzaSiteBundle:Pizza:home" }

pizza_show:
    path:     /{id}/show
    defaults: { _controller: "pizzaSiteBundle:Pizza:show" }

pizza_new:
    path:     /new
    defaults: { _controller: "pizzaSiteBundle:Pizza:new" }

pizza_create:
    path:     /create
    defaults: { _controller: "pizzaSiteBundle:Pizza:create" }
    requirements: { _method: post }

pizza_edit:
    path:     /{id}/edit
    defaults: { _controller: "pizzaSiteBundle:Pizza:edit" }

pizza_update:
    path:     /{id}/update
    defaults: { _controller: "pizzaSiteBundle:Pizza:update" }
    requirements: { _method: post|put }

pizza_delete:
    path:     /{id}/delete
    defaults: { _controller: "pizzaSiteBundle:Pizza:delete" }
    requirements: { _method: post|delete }