rekening:
    path:     /
    defaults: { _controller: "pizzaSiteBundle:Rekening:index" }

rekening_show:
    path:     /{id}/show
    defaults: { _controller: "pizzaSiteBundle:Rekening:show" }

rekening_new:
    path:     /new
    defaults: { _controller: "pizzaSiteBundle:Rekening:new" }

rekening_create:
    path:     /create
    defaults: { _controller: "pizzaSiteBundle:Rekening:create" }
    requirements: { _method: post }

rekening_edit:
    path:     /{id}/edit
    defaults: { _controller: "pizzaSiteBundle:Rekening:edit" }

rekening_update:
    path:     /{id}/update
    defaults: { _controller: "pizzaSiteBundle:Rekening:update" }
    requirements: { _method: post|put }

rekening_delete:
    path:     /{id}/delete
    defaults: { _controller: "pizzaSiteBundle:Rekening:delete" }
    requirements: { _method: post|delete }
