<?php

namespace pizza\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KortingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KortingRepository extends EntityRepository
{
}
